### ISSUE TITLE
QUESTION: Protocol

### ISSUE THREAD

**Issue by karlbeecken** [oism/mmm8x8#1]
Hi!
Can you send me any information about the serial protocol? I'd like to build an information display with MQTT and ESP8266, so it would be very nice if I can use this display and don't have to buy one with open protocol.

Best regards
Karl

**Comment by oism** [comment]
Hi Karl,

the serial protocol is described in ELVJournal 3/2014. You can buy the article here
https://www.elv.de/controller.aspx?cid=726&detail=47175

But you can also look at the source in the mmm8x8 github project, it should give you a
pretty good idea how to use the mmm8x8 with an esp8266.
